<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P5-GKR0N62" name="Test-Smoke" tests="19" failures="6" timestamp="14 Jun 2019 06:14:52 GMT" time="0.192" errors="0">
  <testcase name="test1" time="0.011" classname="TestngFeatures.DemoAssertEquals"/>
  <testcase name="test2" time="0.003" classname="TestngFeatures.DemoAssertEquals">
    <failure type="java.lang.AssertionError" message="Error from test2 expected [Welcome] but found [Hello]">
      <![CDATA[java.lang.AssertionError: Error from test2 expected [Welcome] but found [Hello]
	at TestngFeatures.DemoAssertEquals.test2(DemoAssertEquals.java:17)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.001" classname="TestngFeatures.DemoAssertEquals">
    <failure type="java.lang.AssertionError" message="Object is not null expected object to not be null">
      <![CDATA[java.lang.AssertionError: Object is not null expected object to not be null
	at TestngFeatures.DemoAssertEquals.test3(DemoAssertEquals.java:22)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="TestngFeatures.DemoAssertEquals">
    <failure type="java.lang.AssertionError" message="Intetionally failing the test">
      <![CDATA[java.lang.AssertionError: Intetionally failing the test
	at TestngFeatures.DemoAssertEquals.test4(DemoAssertEquals.java:27)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test1" time="0.002" classname="TestngFeatures.DemoAssertion"/>
  <testcase name="test2" time="0.002" classname="TestngFeatures.DemoAssertion">
    <failure type="java.lang.AssertionError" message="Error from test2-18 greater than 20 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error from test2-18 greater than 20 expected [true] but found [false]
	at TestngFeatures.DemoAssertion.test2(DemoAssertion.java:19)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="TestngFeatures.DemoAssertion">
    <failure type="java.lang.AssertionError" message="Error from -both values are different expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error from -both values are different expected [true] but found [false]
	at TestngFeatures.DemoAssertion.test3(DemoAssertion.java:27)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.004" classname="TestngFeatures.DemoAssertion"/>
  <testcase name="login" time="0.002" classname="TestngFeatures.DemoDataProvider"/>
  <testcase name="login" time="0.006" classname="TestngFeatures.DemoDataProvider"/>
  <testcase name="login" time="0.001" classname="TestngFeatures.DemoDataProvider"/>
  <testcase name="f" time="0.004" classname="TestngFeatures.DemoExecutionSequence"/>
  <testcase name="demo" time="0.01" classname="TestngFeatures.DemoSoftAssertion">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error1 expected [12] but found [10],
	error2 expected [HII] but found [Hello]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Error1 expected [12] but found [10],
	error2 expected [HII] but found [Hello]
	at TestngFeatures.DemoSoftAssertion.demo(DemoSoftAssertion.java:17)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase name="openBrowser" time="0.007" classname="TestngFeatures.MercuryApp"/>
  <testcase name="OpenUrl" time="0.002" classname="TestngFeatures.MercuryApp"/>
  <testcase name="login" time="0.002" classname="TestngFeatures.MercuryApp"/>
  <testcase name="bookFlight" time="0.001" classname="TestngFeatures.MercuryApp"/>
  <testcase name="logout" time="0.001" classname="TestngFeatures.MercuryApp"/>
  <testcase name="close" time="0.003" classname="TestngFeatures.MercuryApp"/>
</testsuite> <!-- Test-Smoke -->
